import { v4 as uuidv4 } from "uuid";

const restaurants = [
  {
    id: uuidv4(),
    name: "Activated charcoal",
    score: 4,
    image: "./restaurant_imgs/pasta.jpg",
    labels: ["artisan", "organic", "chic"],
    gps: 1.4,
    tel: "555-555-555",
  },
  {
    id: uuidv4(),
    name: "Gochujang hexagon",
    score: 2,
    image: "./restaurant_imgs/pancakes.jpg",
    labels: ["artisan", "schlitz"],
    gps: 1.9,
    tel: "555-555-555",
  },
  {
    id: uuidv4(),
    name: "Snackwave",
    score: 5,
    image: "./restaurant_imgs/cake.jpg",
    labels: ["artisan", "organic", "cray"],
    gps: 2.2,
    tel: "555-555-555",
  },
  {
    id: uuidv4(),
    name: "la croix",
    score: 3,
    image: "./restaurant_imgs/hamburger.jpg",
    labels: ["gastropub", "vaporware"],
    gps: 1.1,
    tel: "555-555-555",
  },
  {
    id: uuidv4(),
    name: "pitchfork",
    score: 3,
    image: "./restaurant_imgs/fries.jpg",
    labels: ["vaporware", "gastropub"],
    gps: 2.8,
    tel: "555-555-555",
  },
  {
    id: uuidv4(),
    name: "blue bottle",
    score: 5,
    image: "./restaurant_imgs/lamb.jpg",
    labels: ["artisan", "street"],
    gps: 4.1,
    tel: "555-555-555",
  },
  {
    id: uuidv4(),
    name: "bushwick",
    score: 4,
    image: "./restaurant_imgs/ramen.jpg",
    labels: ["gastropub", "artisan", "freegan"],
    gps: 3.4,
    tel: "555-555-555",
  },
  {
    id: uuidv4(),
    name: "umami",
    score: 4,
    image: "./restaurant_imgs/grill.jpg",
    labels: ["organic", "yolo"],
    gps: 5.7,
    tel: "555-555-555",
  },
  {
    id: uuidv4(),
    name: "stumptown distillery",
    score: 4,
    image: "./restaurant_imgs/wine.jpg",
    labels: ["gastropub", "freegan"],
    gps: 4.7,
    tel: "555-555-555",
  },
  {
    id: uuidv4(),
    name: "hot quinoa",
    score: 3,
    image: "./restaurant_imgs/healthy.jpg",
    labels: ["street", "yolo", "schlitz"],
    gps: 6.0,
    tel: "555-555-555",
  },
  {
    id: uuidv4(),
    name: "squid cloud",
    score: 4,
    image: "./restaurant_imgs/salmon.jpg",
    labels: ["organic", "cray"],
    gps: 4.5,
    tel: "555-555-555",
  },
  {
    id: uuidv4(),
    name: "bird brunch",
    score: 5,
    image: "./restaurant_imgs/yogurt.jpg",
    labels: ["street", "yolo", "organic"],
    gps: 5.1,
    tel: "555-555-555",
  },
];

export default restaurants;
